language: node_js
node_js:
  - 11.6.0
cache: yarn

install:
  - yarn install

script:
  - yarn run build

deploy:
  provider: pages
  cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
