language: node_js
node_js:
  - 11.6.0
cache: yarn

install:
  - yarn install

script:
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: gh-pages
